"""
Django settings for FoodBridge project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import hashlib
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# required by all auth
# SITE_ID=1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'channels',
    'rest_framework',
    'knox',
    'corsheaders',
    'phonenumber_field',
    'django_celery_beat', 

    # 'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',

    # 'dj_rest_auth',
    # 'dj_rest_auth.registration', # If you also want registration endpoints


    'accounts',
    'donations',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FoodBridge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FoodBridge.wsgi.application'
ASGI_APPLICATION = 'FoodBridge.asgi.application'


# AUTHENTICATION_BACKENDS = [
#     # Default Django authentication backend for admin login (username/password)
#     'django.contrib.auth.backends.ModelBackend',
#     # `allauth` specific authentication methods, such as login by e-mail
#     # 'allauth.account.auth_backends.AuthenticationBackend',
# ]

# Allauth general settings
# ACCOUNT_AUTHENTICATION_METHOD = 'email' # or 'username_email' or 'username'
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USERNAME_REQUIRED = False # Often set to False when using email as primary login
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory' # or 'optional' or 'none'
# ACCOUNT_CONFIRM_EMAIL_ON_GET = True # Confirms email on direct click of verification link
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300 # 5 minutes

# # Allauth social account settings (for Google)
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         # For more options, see https://docs.allauth.org/en/latest/socialaccount/providers/google.html
#         'APP': {
#             'client_id': 'YOUR_GOOGLE_WEB_CLIENT_ID.apps.googleusercontent.com', # From Google Cloud Console, type 'Web application'
#             'secret': 'YOUR_GOOGLE_CLIENT_SECRET',
#             'key': '' # Not typically used for Google
#         },
#         'SCOPE': [ # What data you request from Google
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'offline', # To get a refresh token for long-term access
#         }
#     }
# }

# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = '/'
# ACCOUNT_LOGOUT_REDIRECT_URL = '/'

#the  redis server
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # Default Redis URL
# Where Celery stores task results 
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Crucial so that scheduled tasks run at the correct time
CELERY_TIMEZONE = 'Africa/Nairobi'

# Configure Celery Beat to use the database for scheduling
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Optional: You can define fixed schedules here, but using admin is often preferred.
# CELERY_BEAT_SCHEDULE = {
#     'cleanup-expired-donations-daily': {
#         'task': 'donations.tasks.cleanup_expired_donations',
#         'schedule': timedelta(days=1), # Run once a day
#         # 'schedule': timedelta(minutes=5), # For testing, run every 5 minutes
#         'args': (),
#     },
# }



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'accounts.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication options
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # session-based
        'donations.auth.CookieTokenAuthentication',
        # for api access
        'knox.auth.TokenAuthentication',
        # SessionAuthentication if you want browsable API login or traditional Django session
        # 'rest_framework.authentication.SessionAuthentication', # Recommended for DRF browsable API and allauth's session handling
        ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.JSONRenderer',
    #     'rest_framework.renderers.BrowsableAPIRenderer', # For browsable API
    # ),

}

REST_KNOX = {
    'SECURE_HASH_ALGORITHM': hashlib.sha512,
    'AUTH_TOKEN_CHARACTER_LENGTH': 64,
    'TOKEN_TTL': timedelta(hours=10), # Adjust as per your security requirements
    'USER_SERIALIZER': 'donations.serializers.UserSerializer', 
    'TOKEN_LIMIT_PER_USER': None,
    'AUTO_REFRESH': False,
    'EXPIRY_DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
    'TOKEN_KEY_LENGTH': 15, 
}


# REST_AUTH = {
#     'USE_JWT': False, # Set to True if you want JWT, but you're using Knox, so keep False
#     'TOKEN_MODEL': 'knox.models.AuthToken', # Specify Knox as the token model
#     # Specify the Knox serializer if you want custom token data
#     'TOKEN_SERIALIZER': 'dj_rest_auth.serializers.KnoxSerializer',
#     # For social logins to return Knox tokens
#     'OLD_PASSWORD_FIELD_ENABLED': True, # Required for password change
#     'LOGOUT_ON_PASSWORD_CHANGE': True,
#     'PASSWORD_RESET_USE_SITES_DOMAIN': True, # For password reset emails
#     'USER_DETAILS_SERIALIZER': 'users.serializers.CurrentUserSerializer', # Point to your user serializer if you have one
#     # This is crucial for social login with tokens:
#     'SOCIALACCOUNT_ADAPTER': 'dj_rest_auth.social_serializers.SocialAccountAdapter',
# }

# # Email backend for sending emails (for verification, password reset)
# # You need to configure an actual email backend for production!
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # For development: prints emails to console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # For production, e.g. SendGrid, Mailgun


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR,'static')
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, "assets") # for development
# # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# # STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# # media uploads
# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
# ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS =True

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}