# Generated by Django 5.2 on 2025-05-12 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donor_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='shelf_type',
        ),
        migrations.AddField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 19, 13, 2, 59, 689249, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='donationmatch',
            name='shelf_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='available_until',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
