# Generated by Django 5.2 on 2025-06-07 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationmatch_is_missed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 19, 9, 1, 583591, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
