# Generated by Django 5.2 on 2025-06-10 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_is_deleted_alter_donationmatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 17, 5, 13, 47, 697695, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
