# Generated by Django 5.2 on 2025-05-13 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donationmatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 20, 12, 31, 45, 838395, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='required_food_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
