# Generated by Django 5.2 on 2025-06-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donationmatch_expiry_date'),
        ('donations', '0005_alter_donationmatch_expiry_date'),
    ]

    operations = [
    ]
