# Generated by Django 5.2 on 2025-05-14 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donationmatch_expiry_date_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.RemoveField(
            model_name='donationmatch',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='available',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='availability',
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 14, 11, 35, 688271, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='donation',
            name='availability',
            field=models.ManyToManyField(blank=True, related_name='donation_availabilities', to='donations.availability'),
        ),
        migrations.AddField(
            model_name='donationmatch',
            name='selected_availability',
            field=models.ManyToManyField(blank=True, related_name='match_availabilities', to='donations.availability'),
        ),
        migrations.AddField(
            model_name='donor',
            name='general_availability',
            field=models.ManyToManyField(blank=True, related_name='donor_availabilities', to='donations.availability'),
        ),
    ]
