# Generated by Django 5.2 on 2025-05-14 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_availability_remove_donationmatch_pickup_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='specific_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 18, 8, 54, 850227, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
