# Generated by Django 5.2 on 2025-07-22 18:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_donationmatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 29, 18, 34, 4, 891458, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
        migrations.CreateModel(
            name='RecipientNeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.JSONField(blank=True, default=list, null=True)),
                ('quantity', models.FloatField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_logs', to='donations.recipient')),
            ],
        ),
    ]
