# Generated by Django 5.2 on 2025-05-18 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_remove_availability_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='available',
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 25, 13, 26, 50, 12044, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
