# Generated by Django 5.2 on 2025-05-23 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_alter_donationmatch_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmatch',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 22, 24, 6, 369882, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
