# Generated by Django 5.2 on 2025-08-03 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_alter_donation_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AlterField(
            model_name='donation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 10, 19, 25, 4, 552101, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
