# Generated by Django 5.2 on 2025-05-25 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 1, 15, 13, 590705, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
