# Generated by Django 5.2 on 2025-05-25 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationmatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 1, 27, 42, 967780, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
