# Generated by Django 5.2 on 2025-05-25 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_alter_donationmatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 3, 53, 49, 852902, tzinfo=datetime.timezone.utc), help_text='The date when the food will no longer be safe for consumption.', verbose_name='Expiry Date'),
        ),
    ]
